import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import './globals.css';

import { ThemeProvider } from '@mui/material';
import theme from './theme/theme';

const publicsans = Public_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'On The Go',
  description: 'Generated by Leo Pêgo',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={publicsans.className}>
      <head>
        <meta name='viewport' content='initial-scale=1, width=device-width' />
      </head>
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <body>{children}</body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
